// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: InstanceBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_InstanceBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_InstanceBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 8;
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			pAgent_opl.SetVariable<int>("p2", 1462860768u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_InstanceBT_node2 : behaviac.Assignment
	{
		public Assignment_bt_InstanceBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 5;
			behaviac.Agent pAgent_opl = (SecondAgent)AgentMetaVisitor.GetProperty(pAgent, "pInstance");
			pAgent_opl.SetVariable<int>("p2", 1462860768u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_InstanceBT_node3 : behaviac.Condition
	{
		public Condition_bt_InstanceBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent_opl, "p2");
			behaviac.Agent pAgent_opr = (SecondAgent)AgentMetaVisitor.GetProperty(pAgent, "pInstance");
			int opr = (int)AgentMetaVisitor.GetProperty(pAgent_opr, "p2");
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_InstanceBT_node4 : behaviac.Action
	{
		public Action_bt_InstanceBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_InstanceBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("InstanceBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_InstanceBT_node1 node1 = new Assignment_bt_InstanceBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Assignment_bt_InstanceBT_node2 node2 = new Assignment_bt_InstanceBT_node2();
					node2.SetClassNameString("Assignment");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Condition_bt_InstanceBT_node3 node3 = new Condition_bt_InstanceBT_node3();
					node3.SetClassNameString("Condition");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				{
					Action_bt_InstanceBT_node4 node4 = new Action_bt_InstanceBT_node4();
					node4.SetClassNameString("Action");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node4);
					node0.SetHasEvents(node0.HasEvents() | node4.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: LoopBT

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoop_bt_LoopBT_node0 : behaviac.DecoratorLoop
	{
		public DecoratorLoop_bt_LoopBT_node0()
		{
			m_bDecorateWhenChildEnds = true;
			m_bDoneWithinFrame = false;
		}
		protected override int GetCount(Agent pAgent)
		{
			return 3;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_LoopBT_node1 : behaviac.Action
	{
		public Action_bt_LoopBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_LoopBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("LoopBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				DecoratorLoop_bt_LoopBT_node0 node0 = new DecoratorLoop_bt_LoopBT_node0();
				node0.SetClassNameString("DecoratorLoop");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Action_bt_LoopBT_node1 node1 = new Action_bt_LoopBT_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: maintree_task

	[behaviac.GeneratedTypeMetaInfo()]
	class Event_bt_maintree_task_attach5 : behaviac.Event
	{
		public Event_bt_maintree_task_attach5()
		{
			this.Initialize("Self.FirstAgent::event_task(0)", "subtree_task", TriggerMode.TM_Transfer, false);
		}
		public void Initialize(string eventName, string referencedBehavior, TriggerMode mode, bool once)
		{
			this.m_event = AgentMeta.ParseMethod(eventName, ref this.m_eventName);
			this.m_referencedBehaviorPath = referencedBehavior;
			this.m_triggerMode = mode;
			this.m_bTriggeredOnce = once;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_maintree_task_node1 : behaviac.Action
	{
		public Action_bt_maintree_task_node1()
		{
			this.m_resultOption = EBTStatus.BT_RUNNING;
			method_p0 = "Wait subtree...";
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).Say(method_p0);
			return EBTStatus.BT_RUNNING;
		}
		string method_p0;
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_maintree_task_node2 : behaviac.Assignment
	{
		public Assignment_bt_maintree_task_node2()
		{
			m_bCast = true;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 1;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_maintree_task_node3 : behaviac.Condition
	{
		public Condition_bt_maintree_task_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 1;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_maintree_task_node4 : behaviac.Action
	{
		public Action_bt_maintree_task_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = "Hello maintree!";
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).Say(method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		string method_p0;
	}

	public static class bt_maintree_task
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("maintree_task");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				// attachments
				{
					Event_bt_maintree_task_attach5 attach5 = new Event_bt_maintree_task_attach5();
					attach5.SetClassNameString("Event");
					attach5.SetId(5);
#if !BEHAVIAC_RELEASE
					attach5.SetAgentType("FirstAgent");
#endif
					node0.Attach(attach5, false, false, false);
					node0.SetHasEvents(node0.HasEvents() | (attach5 is Event));
				}
				bt.AddChild(node0);
				{
					Action_bt_maintree_task_node1 node1 = new Action_bt_maintree_task_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Assignment_bt_maintree_task_node2 node2 = new Assignment_bt_maintree_task_node2();
					node2.SetClassNameString("Assignment");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Condition_bt_maintree_task_node3 node3 = new Condition_bt_maintree_task_node3();
					node3.SetClassNameString("Condition");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				{
					Action_bt_maintree_task_node4 node4 = new Action_bt_maintree_task_node4();
					node4.SetClassNameString("Action");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node4);
					node0.SetHasEvents(node0.HasEvents() | node4.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: SelectBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_SelectBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_SelectBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 6;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SelectBT_node3 : behaviac.Condition
	{
		public Condition_bt_SelectBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 3;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SelectBT_node4 : behaviac.Action
	{
		public Action_bt_SelectBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_SelectBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SelectBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_SelectBT_node1 node1 = new Assignment_bt_SelectBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Selector node2 = new Selector();
					node2.SetClassNameString("Selector");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_SelectBT_node3 node3 = new Condition_bt_SelectBT_node3();
						node3.SetClassNameString("Condition");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("FirstAgent");
#endif
						node2.AddChild(node3);
						node2.SetHasEvents(node2.HasEvents() | node3.HasEvents());
					}
					{
						Action_bt_SelectBT_node4 node4 = new Action_bt_SelectBT_node4();
						node4.SetClassNameString("Action");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("FirstAgent");
#endif
						node2.AddChild(node4);
						node2.SetHasEvents(node2.HasEvents() | node4.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: subtree_task

	[behaviac.GeneratedTypeMetaInfo()]
	class Task_bt_subtree_task_node0 : behaviac.Task
	{
		public Task_bt_subtree_task_node0()
		{
			this.m_task = AgentMeta.ParseMethod("Self.FirstAgent::event_task(0)");
			Debug.Check(this.m_task != null);
			this.m_bHTN = false;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_subtree_task_node2 : behaviac.Condition
	{
		public Condition_bt_subtree_task_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			Debug.Check(behaviac.Utils.MakeVariableId("_$local_task_param_$_0") == 2009726548u);
			int opl = pAgent.GetVariable<int>(2009726548u);
			int opr = 2;
			bool op = opl == opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_subtree_task_node3 : behaviac.Action
	{
		public Action_bt_subtree_task_node3()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
			method_p0 = "Hello subtree!";
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).Say(method_p0);
			return EBTStatus.BT_SUCCESS;
		}
		string method_p0;
	}

	public static class bt_subtree_task
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("subtree_task");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// locals
			bt.AddLocal("FirstAgent", "int", "_$local_task_param_$_0", "0");
			// children
			{
				Task_bt_subtree_task_node0 node0 = new Task_bt_subtree_task_node0();
				node0.SetClassNameString("Task");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Sequence node1 = new Sequence();
					node1.SetClassNameString("Sequence");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					{
						Condition_bt_subtree_task_node2 node2 = new Condition_bt_subtree_task_node2();
						node2.SetClassNameString("Condition");
						node2.SetId(2);
#if !BEHAVIAC_RELEASE
						node2.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node2);
						node1.SetHasEvents(node1.HasEvents() | node2.HasEvents());
					}
					{
						Action_bt_subtree_task_node3 node3 = new Action_bt_subtree_task_node3();
						node3.SetClassNameString("Action");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("FirstAgent");
#endif
						node1.AddChild(node3);
						node1.SetHasEvents(node1.HasEvents() | node3.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: NullAction

	public static class bt_NullAction
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("NullAction");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Noop node0 = new Noop();
				node0.SetClassNameString("Noop");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
